import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/general/Navbar";
import { AuthProvider } from "@/components/general/AuthProvider";

const urbanist = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${urbanist.variable} ${urbanist.variable} antialiased max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`} >
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
